<div class="div_pi">
    <strong>Ubicados:</strong> En el aula....donde mas.<br/>
    <strong>eMail:</strong> <a href="mailto:merlina@addamsfamily.com?subject=Solicito información">merlina@addamsfamily.com</a><br/>
    <strong>Teléfono:</strong> 88 77 00 99
</div>
<div class="div_pc">
    Carrera de Tecnologías de Información<br/>
    Curso de Tecnologías y Sistemas Web 2<br/>
    Desarrollado completamente a mano con Malicia Indígena
</div>
<div class="div_pd">
    <a href="https://www.facebook.com/"><i class="fa fa-2x fa-facebook"></i></a>
    <br>
    <a href="https://twitter.com/"><i class="fa fa-2x fa-twitter"></i></a>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
